In [36]:
import plotly
plotly.__version__

'3.4.1'

In [37]:
import plotly.plotly as py
from plotly.grid_objs import Grid, Column
from plotly.tools import FigureFactory as FF 

import pandas as pd
import time
plotly.tools.set_credentials_file(username='zhangbojian', api_key='XwpQW8S5WmLaOiLTTQIr')
f = pd.read_csv('USA.csv')

In [38]:
dataset=f

In [39]:
dataset

,Country,Year,Average of Age,Average of Weight,Average of Height,Continent
0,Afghanistan,1936,24.27,NaN,NaN,Asia
1,Afghanistan,1948,NaN,NaN,NaN,Asia
2,Afghanistan,1956,NaN,NaN,NaN,Asia
3,Afghanistan,1960,23.31,69.44,170.69,Asia
4,Afghanistan,1964,22.00,64.25,161.00,Asia
5,Afghanistan,1968,23.20,70.00,170.20,Asia
6,Afghanistan,1972,29.00,63.75,168.33,Asia
7,Afghanistan,1980,23.64,63.18,168.36,Asia
8,Afghanistan,1988,NaN,NaN,NaN,Asia
9,Afghanistan,1996,23.50,NaN,NaN,Asia
10,Afghanistan,2004,18.60,64.75,170.75,Asia
11,Afghanistan,2008,22.50,62.75,179.25,Asia
12,Afghanistan,2012,24.83,60.83,171.67,Asia
13,Afghanistan,2016,24.67,74.00,173.67,Asia
14,Albania,1972,26.80,59.00,NaN,Europe
15,Albania,1992,25.33,75.25,163.00,Europe
16,Albania,1996,26.78,67.50,169.00,Europe
17,Albania,2000,31.20,62.90,167.80,Europe
18,Albania,2004,20.86,70.71,172.29,Europe
19,Albania,2006,19.00,74.00,180.00,Europe
20,Albania,2008,27.25,74.75,173.42,Europe
21,Albania,2010,23.00,74.00,180.00,Europe
22,Albania,2012,25.70,80.20,176.80,Europe
23,Albania,2014,20.00,56.00,163.00,Europe
24,Albania,2016,23.67,67.17,176.17,Europe
25,Algeria,1964,26.00,65.00,175.00,Africa
26,Algeria,1968,25.78,61.22,169.78,Africa
27,Algeria,1972,22.71,63.50,173.17,Africa
28,Algeria,1980,23.37,69.17,175.45,Africa
29,Algeria,1984,24.26,73.32,176.81,Africa
...,...,...,...,...,...,...
3239,Yemen,2008,21.38,55.57,165.43,Asia
3240,Yemen,2012,20.00,58.00,169.00,Asia
3241,Yemen,2016,19.33,65.67,169.67,Asia
3242,Zambia,1964,21.67,68.00,175.73,Africa
3243,Zambia,1968,20.14,60.25,175.25,Africa
3244,Zambia,1972,21.17,58.25,168.50,Africa
3245,Zambia,1980,27.23,67.95,174.21,Africa
3246,Zambia,1984,22.30,67.80,173.71,Africa
3247,Zambia,1988,24.03,68.09,172.78,Africa
3248,Zambia,1992,22.82,64.43,169.71,Africa
3249,Zambia,1996,25.75,60.57,170.17,Africa
3250,Zambia,2000,23.00,64.83,173.17,Africa
3251,Zambia,2004,22.50,64.50,173.67,Africa
3252,Zambia,2008,21.88,62.75,168.71,Africa
3253,Zambia,2012,22.57,74.17,176.17,Africa
3254,Zambia,2016,24.14,67.50,175.17,Africa
3255,Zimbabwe,1928,20.00,NaN,NaN,Africa
3256,Zimbabwe,1960,20.64,62.27,162.82,Africa
3257,Zimbabwe,1964,25.30,70.39,174.45,Africa
3258,Zimbabwe,1980,26.94,70.98,171.94,Africa
3259,Zimbabwe,1984,29.10,67.55,173.95,Africa
3260,Zimbabwe,1988,25.11,70.32,176.49,Africa
3261,Zimbabwe,1992,21.21,62.43,171.14,Africa
3262,Zimbabwe,1996,23.76,68.67,176.71,Africa
3263,Zimbabwe,2000,24.96,71.08,178.96,Africa
3264,Zimbabwe,2004,25.07,70.50,177.79,Africa
3265,Zimbabwe,2008,26.06,63.71,171.93,Africa
3266,Zimbabwe,2012,27.33,65.22,174.44,Africa
3267,Zimbabwe,2014,20.00,81.00,182.00,Africa
3268,Zimbabwe,2016,27.48,62.19,167.84,Africa

In [40]:
years_from_col = set(dataset['Year'])
years_ints = sorted(list(years_from_col))
years = [str(year) for year in years_ints]
#years.remove('1957')

# make list of continents
continents = []
for continent in dataset['Continent']:
    if continent not in continents: 
        continents.append(continent)

columns = []
# make grid
for year in years:
    for continent in continents:
        dataset_by_year = dataset[dataset['Year'] == int(year)]
        dataset_by_year_and_cont = dataset_by_year[dataset_by_year['Continent'] == continent]
        for col_name in dataset_by_year_and_cont:
            # each column name is unique
            column_name = '{year}_{continent}_{header}_gapminder_grid'.format(
                year=year, continent=continent, header=col_name
            )
            a_column = Column(list(dataset_by_year_and_cont[col_name]), column_name)
            columns.append(a_column)

# upload grid
grid = Grid(columns)
url = py.grid_ops.upload(grid, 'gapminder_grid'+str(time.time()), auto_open=False)
url

'https://plot.ly/~zhangbojian/27/'

In [41]:
figure = {
    'data': [],
    'layout': {},
    'frames': [],
    'config': {'scrollzoom': True}
}

# fill in most of layout
figure['layout']['xaxis'] = {'range': [150, 200], 'title': 'Average of Height', 'gridcolor': '#FFFFFF'}
figure['layout']['yaxis'] = {'range': [40, 150],'title': 'Average of Weight', 'gridcolor': '#FFFFFF'}
figure['layout']['hovermode'] = 'closest'
figure['layout']['plot_bgcolor'] = 'rgb(223, 232, 243)'

In [42]:
figure['layout']['sliders'] = {
    'active': 0,
    'yanchor': 'top',
    'xanchor': 'left',
    'currentvalue': {
        'font': {'size': 20},
        'prefix': 'text-before-value-on-display',
        'visible': True,
        'xanchor': 'right'
    },
    'transition': {'duration': 300, 'easing': 'cubic-in-out'},
    'pad': {'b': 10, 't': 50},
    'len': 0.9,
    'x': 0.1,
    'y': 0,
    'steps': [...]
}

In [43]:
{
    'method': 'animate',
    'label': 'label-for-frame',
    'value': 'value-for-frame(defaults to label)',
    'args': [{'frame': {'duration': 300, 'redraw': False},
         'mode': 'immediate'}
    ],
}

{'args': [{'frame': {'duration': 300, 'redraw': False}, 'mode': 'immediate'}],
 'label': 'label-for-frame',
 'method': 'animate',
 'value': 'value-for-frame(defaults to label)'}

In [44]:
sliders_dict = {
    'active': 0,
    'yanchor': 'top',
    'xanchor': 'left',
    'currentvalue': {
        'font': {'size': 20},
        'prefix': 'Year:',
        'visible': True,
        'xanchor': 'right'
    },
    'transition': {'duration': 300, 'easing': 'cubic-in-out'},
    'pad': {'b': 10, 't': 50},
    'len': 0.9,
    'x': 0.1,
    'y': 0,
    'steps': []
}

In [45]:
figure['layout']['updatemenus'] = [
    {
        'buttons': [
            {
                'args': [None, {'frame': {'duration': 500, 'redraw': False},
                         'fromcurrent': True, 'transition': {'duration': 300, 'easing': 'quadratic-in-out'}}],
                'label': 'Play',
                'method': 'animate'
            },
            {
                'args': [[None], {'frame': {'duration': 0, 'redraw': False}, 'mode': 'immediate',
                'transition': {'duration': 0}}],
                'label': 'Pause',
                'method': 'animate'
            }
        ],
        'direction': 'left',
        'pad': {'r': 10, 't': 87},
        'showactive': False,
        'type': 'buttons',
        'x': 0.1,
        'xanchor': 'right',
        'y': 0,
        'yanchor': 'top'
    }
]

custom_colors = {
    'Asia': 'rgb(171, 99, 250)',
    'Europe': 'rgb(230, 99, 250)',
    'Africa': 'rgb(99, 110, 250)',
    'Oceania': 'rgb(25, 211, 243)',
    'North America': 'rgb(50, 170, 255)',
    'South America': 'rgb(150, 70, 255)'
}

In [46]:
col_name_template = '{year}_{continent}_{header}_gapminder_grid'
year = 1896
for continent in continents:
    data_dict = {
        'xsrc': grid.get_column_reference(col_name_template.format(
            year=year, continent=continent, header='Average of Height'
        )),
        'ysrc': grid.get_column_reference(col_name_template.format(
            year=year, continent=continent, header='Average of Weight'
        )),
        'mode': 'markers',
        'textsrc': grid.get_column_reference(col_name_template.format(
            year=year, continent=continent, header='Country'
        )),
        'marker': {
            'sizemode': 'area',
            'sizeref': 0.2,
            'sizesrc': grid.get_column_reference(col_name_template.format(
                 year=year, continent=continent, header='Average of Age'
            )),
            'color': custom_colors[continent]
        },
        'name': continent
    }
    figure['data'].append(data_dict)

In [47]:
figure['layout']['sliders'] = [sliders_dict]

In [48]:
for year in years:
    frame = {'data': [], 'name': str(year)}
    for continent in continents:
        data_dict = {
            'xsrc': grid.get_column_reference(col_name_template.format(
                year=year, continent=continent, header='Average of Height'
            )),
            'ysrc': grid.get_column_reference(col_name_template.format(
                year=year, continent=continent, header='Average of Weight'
            )),
            'mode': 'markers',
            'textsrc': grid.get_column_reference(col_name_template.format(
                year=year, continent=continent, header='Country'
                )),
            'marker': {
                'sizemode': 'area',
                'sizeref': 0.2,
                'sizesrc': grid.get_column_reference(col_name_template.format(
                    year=year, continent=continent, header='Average of Age'
                )),
                'color': custom_colors[continent]
            },
            'name': continent
        }
        frame['data'].append(data_dict)

    figure['frames'].append(frame)
    slider_step = {'args': [
        [year],
        {'frame': {'duration': 300, 'redraw': False},
         'mode': 'immediate',
       'transition': {'duration': 300}}
     ],
     'label': year,
     'method': 'animate'}
    sliders_dict['steps'].append(slider_step)

figure['layout']['sliders'] = [sliders_dict]

In [49]:
py.icreate_animations(figure, 'gapminder_example'+str(time.time()))